/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { RideBooking } from "./RideBooking";
import { RideBookingCountArgs } from "./RideBookingCountArgs";
import { RideBookingFindManyArgs } from "./RideBookingFindManyArgs";
import { RideBookingFindUniqueArgs } from "./RideBookingFindUniqueArgs";
import { DeleteRideBookingArgs } from "./DeleteRideBookingArgs";
import { RideBookingService } from "../rideBooking.service";
@graphql.Resolver(() => RideBooking)
export class RideBookingResolverBase {
  constructor(protected readonly service: RideBookingService) {}

  async _rideBookingsMeta(
    @graphql.Args() args: RideBookingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [RideBooking])
  async rideBookings(
    @graphql.Args() args: RideBookingFindManyArgs
  ): Promise<RideBooking[]> {
    return this.service.rideBookings(args);
  }

  @graphql.Query(() => RideBooking, { nullable: true })
  async rideBooking(
    @graphql.Args() args: RideBookingFindUniqueArgs
  ): Promise<RideBooking | null> {
    const result = await this.service.rideBooking(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => RideBooking)
  async deleteRideBooking(
    @graphql.Args() args: DeleteRideBookingArgs
  ): Promise<RideBooking | null> {
    try {
      return await this.service.deleteRideBooking(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
