/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InsuranceService } from "../insurance.service";
import { InsuranceCreateInput } from "./InsuranceCreateInput";
import { Insurance } from "./Insurance";
import { InsuranceFindManyArgs } from "./InsuranceFindManyArgs";
import { InsuranceWhereUniqueInput } from "./InsuranceWhereUniqueInput";
import { InsuranceUpdateInput } from "./InsuranceUpdateInput";

export class InsuranceControllerBase {
  constructor(protected readonly service: InsuranceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Insurance })
  async createInsurance(
    @common.Body() data: InsuranceCreateInput
  ): Promise<Insurance> {
    return await this.service.createInsurance({
      data: {
        ...data,

        move: {
          connect: data.move,
        },
      },
      select: {
        cost: true,
        coverageAmount: true,
        id: true,

        move: {
          select: {
            id: true,
          },
        },

        policyNumber: true,
        provider: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Insurance] })
  @ApiNestedQuery(InsuranceFindManyArgs)
  async insurances(@common.Req() request: Request): Promise<Insurance[]> {
    const args = plainToClass(InsuranceFindManyArgs, request.query);
    return this.service.insurances({
      ...args,
      select: {
        cost: true,
        coverageAmount: true,
        id: true,

        move: {
          select: {
            id: true,
          },
        },

        policyNumber: true,
        provider: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Insurance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async insurance(
    @common.Param() params: InsuranceWhereUniqueInput
  ): Promise<Insurance | null> {
    const result = await this.service.insurance({
      where: params,
      select: {
        cost: true,
        coverageAmount: true,
        id: true,

        move: {
          select: {
            id: true,
          },
        },

        policyNumber: true,
        provider: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Insurance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInsurance(
    @common.Param() params: InsuranceWhereUniqueInput,
    @common.Body() data: InsuranceUpdateInput
  ): Promise<Insurance | null> {
    try {
      return await this.service.updateInsurance({
        where: params,
        data: {
          ...data,

          move: {
            connect: data.move,
          },
        },
        select: {
          cost: true,
          coverageAmount: true,
          id: true,

          move: {
            select: {
              id: true,
            },
          },

          policyNumber: true,
          provider: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Insurance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInsurance(
    @common.Param() params: InsuranceWhereUniqueInput
  ): Promise<Insurance | null> {
    try {
      return await this.service.deleteInsurance({
        where: params,
        select: {
          cost: true,
          coverageAmount: true,
          id: true,

          move: {
            select: {
              id: true,
            },
          },

          policyNumber: true,
          provider: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
