/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { VehicleService } from "../vehicle.service";
import { VehicleCreateInput } from "./VehicleCreateInput";
import { Vehicle } from "./Vehicle";
import { VehicleFindManyArgs } from "./VehicleFindManyArgs";
import { VehicleWhereUniqueInput } from "./VehicleWhereUniqueInput";
import { VehicleUpdateInput } from "./VehicleUpdateInput";
import { MoveFindManyArgs } from "../../move/base/MoveFindManyArgs";
import { Move } from "../../move/base/Move";
import { MoveWhereUniqueInput } from "../../move/base/MoveWhereUniqueInput";

export class VehicleControllerBase {
  constructor(protected readonly service: VehicleService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Vehicle })
  async createVehicle(
    @common.Body() data: VehicleCreateInput
  ): Promise<Vehicle> {
    return await this.service.createVehicle({
      data: data,
      select: {
        capacityM3: true,
        id: true,
        licensePlate: true,
        make: true,
        model: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Vehicle] })
  @ApiNestedQuery(VehicleFindManyArgs)
  async vehicles(@common.Req() request: Request): Promise<Vehicle[]> {
    const args = plainToClass(VehicleFindManyArgs, request.query);
    return this.service.vehicles({
      ...args,
      select: {
        capacityM3: true,
        id: true,
        licensePlate: true,
        make: true,
        model: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Vehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async vehicle(
    @common.Param() params: VehicleWhereUniqueInput
  ): Promise<Vehicle | null> {
    const result = await this.service.vehicle({
      where: params,
      select: {
        capacityM3: true,
        id: true,
        licensePlate: true,
        make: true,
        model: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Vehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateVehicle(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() data: VehicleUpdateInput
  ): Promise<Vehicle | null> {
    try {
      return await this.service.updateVehicle({
        where: params,
        data: data,
        select: {
          capacityM3: true,
          id: true,
          licensePlate: true,
          make: true,
          model: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Vehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteVehicle(
    @common.Param() params: VehicleWhereUniqueInput
  ): Promise<Vehicle | null> {
    try {
      return await this.service.deleteVehicle({
        where: params,
        select: {
          capacityM3: true,
          id: true,
          licensePlate: true,
          make: true,
          model: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/moves")
  @ApiNestedQuery(MoveFindManyArgs)
  async findMoves(
    @common.Req() request: Request,
    @common.Param() params: VehicleWhereUniqueInput
  ): Promise<Move[]> {
    const query = plainToClass(MoveFindManyArgs, request.query);
    const results = await this.service.findMoves(params.id, {
      ...query,
      select: {
        costDistance: true,
        costVolume: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        date: true,
        distanceKm: true,

        feedback: {
          select: {
            id: true,
          },
        },

        id: true,
        status: true,
        totalCost: true,
        updatedAt: true,

        vehicle: {
          select: {
            id: true,
          },
        },

        volumeM3: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/moves")
  async connectMoves(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: MoveWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      moves: {
        connect: body,
      },
    };
    await this.service.updateVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/moves")
  async updateMoves(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: MoveWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      moves: {
        set: body,
      },
    };
    await this.service.updateVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/moves")
  async disconnectMoves(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: MoveWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      moves: {
        disconnect: body,
      },
    };
    await this.service.updateVehicle({
      where: params,
      data,
      select: { id: true },
    });
  }
}
