/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BudgetWhereUniqueInput } from "../../budget/base/BudgetWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  IsNumber,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { CostSimulationCreateNestedManyWithoutMovesInput } from "./CostSimulationCreateNestedManyWithoutMovesInput";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { DriverWhereUniqueInput } from "../../driver/base/DriverWhereUniqueInput";
import { GpsDatumCreateNestedManyWithoutMovesInput } from "./GpsDatumCreateNestedManyWithoutMovesInput";
import { PaymentCreateNestedManyWithoutMovesInput } from "./PaymentCreateNestedManyWithoutMovesInput";
import { RouteWhereUniqueInput } from "../../route/base/RouteWhereUniqueInput";
import { EnumMoveStatus } from "./EnumMoveStatus";

@InputType()
class MoveCreateInput {
  @ApiProperty({
    required: false,
    type: () => BudgetWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => BudgetWhereUniqueInput)
  @IsOptional()
  @Field(() => BudgetWhereUniqueInput, {
    nullable: true,
  })
  budget?: BudgetWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  completedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => CostSimulationCreateNestedManyWithoutMovesInput,
  })
  @ValidateNested()
  @Type(() => CostSimulationCreateNestedManyWithoutMovesInput)
  @IsOptional()
  @Field(() => CostSimulationCreateNestedManyWithoutMovesInput, {
    nullable: true,
  })
  costSimulation?: CostSimulationCreateNestedManyWithoutMovesInput;

  @ApiProperty({
    required: true,
    type: () => CustomerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CustomerWhereUniqueInput)
  @Field(() => CustomerWhereUniqueInput)
  customer!: CustomerWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  deliveryLocation!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  distance!: number;

  @ApiProperty({
    required: false,
    type: () => DriverWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DriverWhereUniqueInput)
  @IsOptional()
  @Field(() => DriverWhereUniqueInput, {
    nullable: true,
  })
  driver?: DriverWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => GpsDatumCreateNestedManyWithoutMovesInput,
  })
  @ValidateNested()
  @Type(() => GpsDatumCreateNestedManyWithoutMovesInput)
  @IsOptional()
  @Field(() => GpsDatumCreateNestedManyWithoutMovesInput, {
    nullable: true,
  })
  gpsData?: GpsDatumCreateNestedManyWithoutMovesInput;

  @ApiProperty({
    required: false,
    type: () => PaymentCreateNestedManyWithoutMovesInput,
  })
  @ValidateNested()
  @Type(() => PaymentCreateNestedManyWithoutMovesInput)
  @IsOptional()
  @Field(() => PaymentCreateNestedManyWithoutMovesInput, {
    nullable: true,
  })
  payments?: PaymentCreateNestedManyWithoutMovesInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  pickupLocation!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  price!: number;

  @ApiProperty({
    required: false,
    type: () => RouteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RouteWhereUniqueInput)
  @IsOptional()
  @Field(() => RouteWhereUniqueInput, {
    nullable: true,
  })
  route?: RouteWhereUniqueInput | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  scheduledAt!: Date;

  @ApiProperty({
    required: true,
    enum: EnumMoveStatus,
  })
  @IsEnum(EnumMoveStatus)
  @Field(() => EnumMoveStatus)
  status!: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "CANCELED";

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  volume!: number;
}

export { MoveCreateInput as MoveCreateInput };
