/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Move } from "./Move";
import { MoveCountArgs } from "./MoveCountArgs";
import { MoveFindManyArgs } from "./MoveFindManyArgs";
import { MoveFindUniqueArgs } from "./MoveFindUniqueArgs";
import { CreateMoveArgs } from "./CreateMoveArgs";
import { UpdateMoveArgs } from "./UpdateMoveArgs";
import { DeleteMoveArgs } from "./DeleteMoveArgs";
import { CostSimulationFindManyArgs } from "../../costSimulation/base/CostSimulationFindManyArgs";
import { CostSimulation } from "../../costSimulation/base/CostSimulation";
import { GpsDatumFindManyArgs } from "../../gpsDatum/base/GpsDatumFindManyArgs";
import { GpsDatum } from "../../gpsDatum/base/GpsDatum";
import { Budget } from "../../budget/base/Budget";
import { Customer } from "../../customer/base/Customer";
import { Driver } from "../../driver/base/Driver";
import { Route } from "../../route/base/Route";
import { MoveService } from "../move.service";
@graphql.Resolver(() => Move)
export class MoveResolverBase {
  constructor(protected readonly service: MoveService) {}

  async _movesMeta(
    @graphql.Args() args: MoveCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Move])
  async moves(@graphql.Args() args: MoveFindManyArgs): Promise<Move[]> {
    return this.service.moves(args);
  }

  @graphql.Query(() => Move, { nullable: true })
  async move(@graphql.Args() args: MoveFindUniqueArgs): Promise<Move | null> {
    const result = await this.service.move(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Move)
  async createMove(@graphql.Args() args: CreateMoveArgs): Promise<Move> {
    return await this.service.createMove({
      ...args,
      data: {
        ...args.data,

        budget: args.data.budget
          ? {
              connect: args.data.budget,
            }
          : undefined,

        customer: {
          connect: args.data.customer,
        },

        driver: args.data.driver
          ? {
              connect: args.data.driver,
            }
          : undefined,

        route: args.data.route
          ? {
              connect: args.data.route,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Move)
  async updateMove(@graphql.Args() args: UpdateMoveArgs): Promise<Move | null> {
    try {
      return await this.service.updateMove({
        ...args,
        data: {
          ...args.data,

          budget: args.data.budget
            ? {
                connect: args.data.budget,
              }
            : undefined,

          customer: {
            connect: args.data.customer,
          },

          driver: args.data.driver
            ? {
                connect: args.data.driver,
              }
            : undefined,

          route: args.data.route
            ? {
                connect: args.data.route,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Move)
  async deleteMove(@graphql.Args() args: DeleteMoveArgs): Promise<Move | null> {
    try {
      return await this.service.deleteMove(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [CostSimulation], { name: "costSimulation" })
  async findCostSimulation(
    @graphql.Parent() parent: Move,
    @graphql.Args() args: CostSimulationFindManyArgs
  ): Promise<CostSimulation[]> {
    const results = await this.service.findCostSimulation(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [GpsDatum], { name: "gpsData" })
  async findGpsData(
    @graphql.Parent() parent: Move,
    @graphql.Args() args: GpsDatumFindManyArgs
  ): Promise<GpsDatum[]> {
    const results = await this.service.findGpsData(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Budget, {
    nullable: true,
    name: "budget",
  })
  async getBudget(@graphql.Parent() parent: Move): Promise<Budget | null> {
    const result = await this.service.getBudget(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Customer, {
    nullable: true,
    name: "customer",
  })
  async getCustomer(@graphql.Parent() parent: Move): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Driver, {
    nullable: true,
    name: "driver",
  })
  async getDriver(@graphql.Parent() parent: Move): Promise<Driver | null> {
    const result = await this.service.getDriver(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Route, {
    nullable: true,
    name: "route",
  })
  async getRoute(@graphql.Parent() parent: Move): Promise<Route | null> {
    const result = await this.service.getRoute(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
