/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Move } from "./Move";
import { MoveCountArgs } from "./MoveCountArgs";
import { MoveFindManyArgs } from "./MoveFindManyArgs";
import { MoveFindUniqueArgs } from "./MoveFindUniqueArgs";
import { CreateMoveArgs } from "./CreateMoveArgs";
import { UpdateMoveArgs } from "./UpdateMoveArgs";
import { DeleteMoveArgs } from "./DeleteMoveArgs";
import { MoveEmployeeFindManyArgs } from "../../moveEmployee/base/MoveEmployeeFindManyArgs";
import { MoveEmployee } from "../../moveEmployee/base/MoveEmployee";
import { InsuranceFindManyArgs } from "../../insurance/base/InsuranceFindManyArgs";
import { Insurance } from "../../insurance/base/Insurance";
import { ItemFindManyArgs } from "../../item/base/ItemFindManyArgs";
import { Item } from "../../item/base/Item";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { RouteFindManyArgs } from "../../route/base/RouteFindManyArgs";
import { Route } from "../../route/base/Route";
import { StorageFindManyArgs } from "../../storage/base/StorageFindManyArgs";
import { Storage } from "../../storage/base/Storage";
import { Customer } from "../../customer/base/Customer";
import { Feedback } from "../../feedback/base/Feedback";
import { Vehicle } from "../../vehicle/base/Vehicle";
import { MoveService } from "../move.service";
@graphql.Resolver(() => Move)
export class MoveResolverBase {
  constructor(protected readonly service: MoveService) {}

  async _movesMeta(
    @graphql.Args() args: MoveCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Move])
  async moves(@graphql.Args() args: MoveFindManyArgs): Promise<Move[]> {
    return this.service.moves(args);
  }

  @graphql.Query(() => Move, { nullable: true })
  async move(@graphql.Args() args: MoveFindUniqueArgs): Promise<Move | null> {
    const result = await this.service.move(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Move)
  async createMove(@graphql.Args() args: CreateMoveArgs): Promise<Move> {
    return await this.service.createMove({
      ...args,
      data: {
        ...args.data,

        customer: {
          connect: args.data.customer,
        },

        feedback: args.data.feedback
          ? {
              connect: args.data.feedback,
            }
          : undefined,

        vehicle: args.data.vehicle
          ? {
              connect: args.data.vehicle,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Move)
  async updateMove(@graphql.Args() args: UpdateMoveArgs): Promise<Move | null> {
    try {
      return await this.service.updateMove({
        ...args,
        data: {
          ...args.data,

          customer: {
            connect: args.data.customer,
          },

          feedback: args.data.feedback
            ? {
                connect: args.data.feedback,
              }
            : undefined,

          vehicle: args.data.vehicle
            ? {
                connect: args.data.vehicle,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Move)
  async deleteMove(@graphql.Args() args: DeleteMoveArgs): Promise<Move | null> {
    try {
      return await this.service.deleteMove(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [MoveEmployee], { name: "employees" })
  async findEmployees(
    @graphql.Parent() parent: Move,
    @graphql.Args() args: MoveEmployeeFindManyArgs
  ): Promise<MoveEmployee[]> {
    const results = await this.service.findEmployees(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Insurance], { name: "insurance" })
  async findInsurance(
    @graphql.Parent() parent: Move,
    @graphql.Args() args: InsuranceFindManyArgs
  ): Promise<Insurance[]> {
    const results = await this.service.findInsurance(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Item], { name: "items" })
  async findItems(
    @graphql.Parent() parent: Move,
    @graphql.Args() args: ItemFindManyArgs
  ): Promise<Item[]> {
    const results = await this.service.findItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Payment], { name: "payment" })
  async findPayment(
    @graphql.Parent() parent: Move,
    @graphql.Args() args: PaymentFindManyArgs
  ): Promise<Payment[]> {
    const results = await this.service.findPayment(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Route], { name: "route" })
  async findRoute(
    @graphql.Parent() parent: Move,
    @graphql.Args() args: RouteFindManyArgs
  ): Promise<Route[]> {
    const results = await this.service.findRoute(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Storage], { name: "storage" })
  async findStorage(
    @graphql.Parent() parent: Move,
    @graphql.Args() args: StorageFindManyArgs
  ): Promise<Storage[]> {
    const results = await this.service.findStorage(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Customer, {
    nullable: true,
    name: "customer",
  })
  async getCustomer(@graphql.Parent() parent: Move): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Feedback, {
    nullable: true,
    name: "feedback",
  })
  async getFeedback(@graphql.Parent() parent: Move): Promise<Feedback | null> {
    const result = await this.service.getFeedback(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Vehicle, {
    nullable: true,
    name: "vehicle",
  })
  async getVehicle(@graphql.Parent() parent: Move): Promise<Vehicle | null> {
    const result = await this.service.getVehicle(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
