/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsEnum } from "class-validator";
import { RatingUpdateManyWithoutUsersInput } from "./RatingUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { EnumUserRole } from "./EnumUserRole";
import { SupportTicketUpdateManyWithoutUsersInput } from "./SupportTicketUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string;

  @ApiProperty({
    required: false,
    type: () => RatingUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => RatingUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => RatingUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  ratingsGiven?: RatingUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => RatingUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => RatingUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => RatingUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  ratingsReceived?: RatingUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    enum: EnumUserRole,
  })
  @IsEnum(EnumUserRole)
  @IsOptional()
  @Field(() => EnumUserRole, {
    nullable: true,
  })
  role?: "ADMIN" | "DRIVER" | "CUSTOMER";

  @ApiProperty({
    required: false,
    type: () => SupportTicketUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SupportTicketUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SupportTicketUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  supportTicket?: SupportTicketUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
